
# Credit Risk Prediction using Artificial Neural Network (ANN)

## Project Objective
Build a Deep Learning model to predict loan approval status using structured financial data.

Dataset: Credit Risk Dataset (Kaggle)
Target Variable: `loan_status`
- 1 = High Risk (Rejected)
- 0 = Low Risk (Approved)

## 1️⃣ Import Required Libraries

In [ ]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

## 2️⃣ Load the Dataset

In [ ]:

data = pd.read_csv("credit_risk_dataset.csv")
print("Dataset Shape:", data.shape)
data.head()

Dataset Shape: (32581, 12)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4


## 3️⃣ Data Preprocessing

- Remove missing values
- Convert categorical variables using one-hot encoding
- Separate features and target

In [ ]:

# Remove missing values
data = data.dropna()

# Convert categorical columns
categorical_cols = [
    'person_home_ownership',
    'loan_intent',
    'loan_grade',
    'cb_person_default_on_file'
]

data = pd.get_dummies(data, columns=categorical_cols, drop_first=True)

# Split features & target
X = data.drop("loan_status", axis=1)
y = data["loan_status"]

X.head()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,...,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,loan_grade_B,loan_grade_C,loan_grade_D,loan_grade_E,loan_grade_F,loan_grade_G,cb_person_default_on_file_Y
0,22,59000,123.0,35000,16.02,0.59,3,False,False,True,...,False,True,False,False,False,True,False,False,False,True
1,21,9600,5.0,1000,11.14,0.10,2,False,True,False,...,False,False,False,True,False,False,False,False,False,False
2,25,9600,1.0,5500,12.87,0.57,3,False,False,False,...,True,False,False,False,True,False,False,False,False,False
3,23,65500,4.0,35000,15.23,0.53,2,False,False,True,...,True,False,False,False,True,False,False,False,False,False
4,24,54400,8.0,35000,14.27,0.55,4,False,False,True,...,True,False,False,False,True,False,False,False,False,True

## 4️⃣ Train-Test Split

In [ ]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)

Training shape: (22910, 22)
Testing shape: (5728, 22)

## 5️⃣ Feature Scaling

In [ ]:

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


## 6️⃣ Build the Artificial Neural Network (ANN)

Architecture:
- Dense (128 neurons, ReLU)
- Dropout (0.3)
- Dense (64 neurons, ReLU)
- Dropout (0.2)
- Dense (32 neurons, ReLU)
- Output (1 neuron, Sigmoid)

In [ ]:

model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         2,944 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13,313 (52.00 KB)

 Trainable params: 13,313 (52.00 KB)

 Non-trainable params: 0 (0.00 B)

## 7️⃣ Train the Model

In [ ]:

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=32,
    callbacks=[early_stop]
)

Epoch 1/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8228 - loss: 0.4164 - val_accuracy: 0.8937 - val_loss: 0.2926
Epoch 2/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8871 - loss: 0.3053 - val_accuracy: 0.9042 - val_loss: 0.2750
Epoch 3/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8972 - loss: 0.2855 - val_accuracy: 0.9066 - val_loss: 0.2670
Epoch 4/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9035 - loss: 0.2706 - val_accuracy: 0.9110 - val_loss: 0.2578
Epoch 5/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9086 - loss: 0.2622 - val_accuracy: 0.9158 - val_loss: 0.2423
Epoch 6/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9081 - loss: 0.2607 - val_accuracy: 0.9171 - val_loss: 0.2393
Epoch 7/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9159 - loss: 0.2459 - val_accuracy: 0.9203 - val_loss: 0.2390
Epoch 8/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9134 - loss: 0.2431 - val_accuracy: 0.9177 - val_loss: 0.2429
Epoch 9/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9169 - loss: 0.2434 - val_accuracy: 0.9184 - val_loss: 0.2357
Epoch 10/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9169 - loss: 0.2422 - val_accuracy: 0.9203 - val_loss: 0.2309
Epoch 11/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9170 - loss: 0.2362 - val_accuracy: 0.9210 - val_loss: 0.2297
Epoch 12/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9191 - loss: 0.2359 - val_accuracy: 0.9216 - val_loss: 0.2334
Epoch 13/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9243 - loss: 0.2249 - val_accuracy: 0.9203 - val_loss: 0.2318
Epoch 14/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9209 - loss: 0.2331 - val_accuracy: 0.9199 - val_loss: 0.2314
Epoch 15/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9211 - loss: 0.2319 - val_accuracy: 0.9210 - val_loss: 0.2304
Epoch 16/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9219 - loss: 0.2299 - val_accuracy: 0.9230 - val_loss: 0.2288
Epoch 17/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9236 - loss: 0.2283 - val_accuracy: 0.9212 - val_loss: 0.2293
Epoch 18/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9249 - loss: 0.2221 - val_accuracy: 0.9249 - val_loss: 0.2261
Epoch 19/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9221 - loss: 0.2254 - val_accuracy: 0.9232 - val_loss: 0.2249
Epoch 20/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9232 - loss: 0.2288 - val_accuracy: 0.9208 - val_loss: 0.2290
Epoch 21/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9215 - loss: 0.2275 - val_accuracy: 0.9227 - val_loss: 0.2276
Epoch 22/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9252 - loss: 0.2204 - val_accuracy: 0.9247 - val_loss: 0.2255
Epoch 23/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9260 - loss: 0.2187 - val_accuracy: 0.9223 - val_loss: 0.2269
Epoch 24/50
573/573 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9224 - loss: 0.2320 - val_accuracy: 0.9227 - val_loss: 0.2262

## 8️⃣ Evaluate the Model

In [ ]:

loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

y_pred = (model.predict(X_test) > 0.5).astype(int)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("ROC-AUC Score:", roc_auc_score(y_test, y_pred))

179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9200 - loss: 0.2307
Test Accuracy: 0.9188198447227478
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

Confusion Matrix:
[[4401   42]
 [ 423  862]]

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.99      0.95      4443
           1       0.95      0.67      0.79      1285

    accuracy                           0.92      5728
   macro avg       0.93      0.83      0.87      5728
weighted avg       0.92      0.92      0.91      5728

ROC-AUC Score: 0.8306820241870436


## ✅ Conclusion

This ANN model captures nonlinear financial relationships between:
- Income
- Loan amount
- Credit history
- Employment length

Deep Learning performs well for structured financial risk modeling.